[package]
name = "drop_example"
version = "0.1.0"
authors = ["Lakshmi Narayanan N <grabyourfreedom@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
